### ISSUE TITLE
Display is too wide for 1366x768

### ISSUE THREAD

**Issue by da0ist** [elvetemedve/gnome-shell-extension-system-monitor#41] opened 2017-11-06 20:14 UTC
1366x768 is the maximum resolution several of my ThinkPads. This is what I see:

![screenshot from 2017-11-06 13-13-40](https://user-images.githubusercontent.com/7945846/32461813-56c58234-c2f4-11e7-933f-6c79734674b4.png)

**Comment by elvetemedve** [comment] 2017-11-06 20:22
It's a duplicate of https://github.com/elvetemedve/gnome-shell-extension-system-monitor/issues/10.

**Comment by da0ist** [comment] 2020-07-14 17:19
It's a duplicate of #10.

**Closed** 2020-07-14 17:18 UTC
